import { PrinterInterface } from '../utilities/interfaces';

export const printers: PrinterInterface[] = [
  { id:'1515',
    ip:'asd',
    area: 'tak',
    model: 'Xerox_AltaLink_C8035',
    title:'ads',
    multifunctional: true,
    location:'adsads',
  },
  { id:'1516',
    ip:'asd',
    area: 'tak',
    model: 'Xerox_AltaLink_C8035',
    title:'ads',
    multifunctional: true,
    location:'adsads',
  },
  { id:'1515',
    ip:'asd',
    area: 'tak',
    model: 'Xerox_AltaLink_C8035',
    title:'ads',
    multifunctional: true,
    location:'adsads',
  },
  { id:'1515',
    ip:'asd',
    area: 'tak',
    model: 'Xerox_AltaLink_C8035',
    title:'ads',
    multifunctional: true,
    location:'adsads',
  },
  { id:'1515',
    ip:'asd',
    area: 'tak',
    model: 'Xerox_AltaLink_C8035',
    title:'ads',
    multifunctional: true,
    location:'adsads',
  },
];
